"""
List of English contractions, lower cased
"""

CONTRACTIONS = {
    "aren't": "are not",
    "she'd": "she had",
    "can't": "cannot",
    "shouldn't": "should not",
    "couldn't": "could not",
    "that's": "that is",
    "didn't": "did not",
    "there's": "there is",
    "don't": "do not",
    "they're": "they are",
    "doesn't": "does not",
    "they've": "they have",
    "hadn't": "had not",
    "they'll": "they will",
    "haven't": "have not",
    "they'd": "they would",
    "he's": "he is",
    "wasn't": "was not",
    "he'll": "he will",
    "we're": "we are",
    "he'd": "he would",
    "we've": "we have",
    "here's": "here is",
    "we'll": "we will",
    "i'm": "i am",
    "we'd": "we would",
    "i've": "i have",
    "i'll": "i will",
    "weren't": "were not",
    "i'd": "i would",
    "what's": "what is",
    "where's": "where is",
    "isn't": "is not",
    "who's": "who is",
    "it's": "it is",
    "who'll": "who will",
    "won't": "will not",
    "wouldn't": "would not",
    "it'll": "it will",
    "you're": "you are",
    "mustn't": "must not",
    "you've": "you have",
    "she's": "she is",
    "you'll": "you will",
    "you'd": "you would",
    "she'll": "she will",
    "a'ight": "alright",
    "ain't": "are not",
    "amn't": "am not",
    "arencha": "are not you",
    "'bout": "about",
    "cannot": "can not",
    "cap'n": "captain",
    "'cause": "because",
    "'cept": "except",
    "could've": "could have",
    "couldn't've": "could not have",
    "dammit": "damn it",
    "daren't": "dare not",
    "daresn't": "dare not",
    "dasn't": "dare not",
    "dunno": "do not know",
    "d'ye": "do you",
    "e'en": "even",
    "e'er": "ever",
    "'em": "them",
    "everybody's": "everybody is",
    "everyone's": "everyone is",
    "fo'c'sle": "forecastle",
    "'gainst": "against",
    "g'day": "good day",
    "gimme": "give me",
    "giv'n": "given",
    "gonna": "going to",
    "gon't": "go not (colloquial)",
    "gotta": "got to",
    "had've": "had have",
    "hasn't": "has not",
    "helluva": "hell of a",
    "how'd": "how did",
    "howdy": "how do you do",
    "how'll": "how will",
    "how're": "how are",
    "how's": "how has",
    "i'd've": "i would have",
    "imma": "i am about to",
    "i'm'o": "i am going to",
    "innit": "is it not",
    "ion": "i do not",
    "it'd": "it would",
    "iunno": "i don't know",
    "kinda": "kind of",
    "let's": "let us",
    "ma'am": "madam",
    "mayn't": "may not",
    "may've": "may have",
    "methinks": "i think",
    "mightn't": "might not",
    "might've": "might have",
    "mustn't've": "must not have",
    "must've": "must have",
    "'neath": "beneath",
    "needn't": "need not",
    "nal": "and all",
    "ne'er": "never",
    "o'clock": "of the clock",
    "o'er": "over",
    "ol'": "old",
    "oughtn't": "ought not",
    "'round": "around",
    "'s": "is",
    "shalln't": "shall not",
    "shan't": "shall not",
    "should've": "should have",
    "shouldn't've": "should not have",
    "somebody's": "somebody has",
    "someone's": "someone has",
    "something's": "something has",
    "so're": "so are",
    "so's": "so is",
    "so've": "so have",
    "that'll": "that will",
    "that're": "that are",
    "that'd": "that would",
    "there'd": "there had",
    "there'll": "there will",
    "there're": "there are",
    "these're": "these are",
    "these've": "these have",
    "this's": "this has",
    "those're": "those are",
    "those've": "those have",
    "'thout": "without",
    "'til": "until",
    "'tis": "it is",
    "to've": "to have",
    "'twas": "it was",
    "'tween": "between",
    "'twere": "it were",
    "wanna": "want to",
    "we'd've": "we would have",
    "whatcha": "what are you",
    "what'd": "what did",
    "what'll": "what will",
    "what're": "what are",
    "what've": "what have",
    "when's": "when has",
    "where'd": "where did",
    "where'll": "where will",
    "where're": "where are",
    "where've": "where have",
    "which'd": "which had",
    "which'll": "which will",
    "which're": "which are",
    "which's": "which has",
    "which've": "which have",
    "who'd": "who would",
    "who'd've": "who would have",
    "who're": "who are",
    "who've": "who have",
    "why'd": "why did",
    "why're": "why are",
    "why's": "why has",
    "willn't": "will not",
    "wonnot": "will not",
    "would've": "would have",
    "wouldn't've": "would not have",
    "y'all": "you all",
    "y'all'd've": "you all would have",
    "y'all'd'n't've": "you all would not have",
    "y'all're": "you all are",
    "y'all'ren't": "you all are not",
    "y'at": "you at",
    "yes'm": "yes madam",
    "yessir": "yes sir",
}
